### ISSUE TITLE
reporting: enable logging & skipping of unrecognised probes, detectors in digest generation

### ISSUE THREAD

**Issue by leondz** [NVIDIA/garak#1024]
## Summary

If an unknown probe or detector is encountered in `report_digest`, due for example to version mismatches, it fails. Would be cool if it didn't.

### Basic example

Here, the plugin name's shifted from `ContinueSlursReclaimedSlurs80` to ContinueSlursReclaimedSlursMini`:

```
(garak) 10:04:50 x1:~/dev/garak [main] $ python -m garak.analyze.report_digest hymba.jsonl > hymba.html
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/lderczynski/dev/garak/garak/analyze/report_digest.py", line 292, in <module>
    digest_content = compile_digest(report_path, taxonomy=taxonomy)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lderczynski/dev/garak/garak/analyze/report_digest.py", line 201, in compile_digest
    getattr(pm, probe_class).__doc__
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'garak.probes.continuation' has no attribute 'ContinueSlursReclaimedSlurs80'. Did you mean: 'ContinueSlursReclaimedSlurs'?
```

Would be cool if we notified on stderr and in the report, and continued on, instead of breaking like this.

### Motivation

To enable reports to be generated even if not all the source data can be processed as we'd like

**Comment by precognitivem0nk** [comment]
Hi, I'd like to take this on. 

I've looked into the current codebase and the code has been refactored since this issue was filed. The getattr calls have been replaced with PluginCache.plugin_info(), but there's still no error handling around them. I identified three unguarded call sites in report_digest.py (in _init_populate_result_db, _get_probe_info, and _get_probe_detector_details) that raise a ValueError when a referenced probe or detector no longer exists in the plugin cache. 

My fix wraps each call in try/except, logs a warning, and continues report generation with placeholder values. I've verified the fix against a JSONL file referencing a nonexistent probe and confirmed it produces a valid HTML report with the appropriate warnings. PR coming shortly
