### ISSUE TITLE
probes: fileformats probe fails when targeting a local modal path

### ISSUE THREAD

**Issue by jmartin-tech** [NVIDIA/garak#1034]
The `fileformats` are limited to huggingface generators, however there are cases where the generator can load a local checkpoint that would not be complatible with this probe. This is due the the expectation that the model under test is published for file enumeration via the `huggingface_hub` utility library.

Contrived example:
```
python -m garak -m huffingface.Model -n /usr/local/checkpoints/Mistral-NeMo-Minitron-8B-Instruct -p fileformats
```

Current trace reported in logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/garak/cli.py", line 530, in main
    command.probewise_run(
  File "/usr/local/lib/python3.10/site-packages/garak/command.py", line 237, in probewise_run
    probewise_h.run(generator, probe_names, evaluator, buffs)
  File "/usr/local/lib/python3.10/site-packages/garak/harnesses/probewise.py", line 107, in run
    h.run(model, [probe], detectors, evaluator, announce_probe=False)
  File "/usr/local/lib/python3.10/site-packages/garak/harnesses/base.py", line 114, in run
    attempt_results = probe.probe(model)
  File "/usr/local/lib/python3.10/site-packages/garak/probes/fileformats.py", line 63, in probe
    repo_filenames = huggingface_hub.list_repo_files(generator.name)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/usr/local/checkpoints/Mistral-NeMo-Minitron-8B-Instruct/'. Use `repo_type` argument if needed.
```

This probe needs to be able to either skip for `local` model paths or follow an alternative file gathering approach.

**Comment by JanetVictorious** [comment]
I had a similar problem with the atkgen probe. I got around this issue by adding the following env variables with the execution:

```bash
HF_DATASETS_OFFLINE=1 \
HF_HUB_OFFLINE=1 \
HF_HOME=/path/to/hf_home \
python -m garak -m huggingface.Model -n namespace/repo_name -p atkgen
```

Then garak was able to load my local model without having to provide the path to the model checkpoint and it was able to use the  namespace/repo_name.

**Comment by CrepuscularIRIS** [comment]
Hi — I'd like to take this one if it's still open.

Root cause looks contained: `HF_Files.probe()` calls `huggingface_hub.list_repo_files(generator.name)` unconditionally, so `HFValidationError` propagates whenever `generator.name` is a local path rather than a hub id. Proposed approach is to validate the name with `huggingface_hub.utils.validate_repo_id` up front and, on failure, log a short info message and return `[]` — the probe has nothing to enumerate when it can't talk to the Hub about this target. I'd add a small unit test that exercises the local-path case without needing network.

Happy to scope it differently (e.g. an alternative file-enumeration path) if that's closer to the intent.

**Comment by jmartin-tech** [comment]
@CrepuscularIRIS, I would hazard that detecting a local path was provide for the model name and forcing a local load by injecting the offline mode restrictions should be enough to resolve the issue. Calling `huggingface_hub.utils.validate_repo_id` really should only be needed if the provided name is _ambiguous_ when attempting to evaluate if it is a local path to a model on disk.
