### ISSUE TITLE
Zsh raise Exception( API Key Failure from os.getenv()

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [NVIDIA/garak#105]
After adding `COHERE_API_KEY` to `.env` within `zsh`, the script fails to identify the environment variable with error:

```
   File "*garak/garak/generators/cohere.py", line 38, in __init__
     raise Exception(
 Exception: Put the Cohere API key in the COHERE_API_KEY environment variable (this was empty)
                  e.g.: export COHERE_API_KEY="XXXXXXX"
```

Believe I found the issue in `os.getenv()` I believe.

[Here](https://github.com/leondz/garak/blob/main/garak/generators/cohere.py#L36)

This does not look to be related specifically to the type of `API_KEY` / `--module` specific etc.

As discussed with Leon, taking a look.

**Comment by leondz** [comment]
running export in zsh seemed to fix this:

```
(garak) leod@mac622226 garak % python3 -m garak -m cohere -p test.Blank
garak LLM probe v0.9 ( https://github.com/leondz/garak ) at 2023-06-08T22:25:34.470323
📜 reporting to garak.777273.jsonl
🦜 loading generator: Cohere: command
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/leod/Dropbox/dev/garak/garak/__main__.py", line 13, in <module>
    main()
  File "/Users/leod/Dropbox/dev/garak/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/Users/leod/Dropbox/dev/garak/garak/cli.py", line 188, in main
    generator = getattr(generator_mod, generator_class_name)()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leod/Dropbox/dev/garak/garak/generators/cohere.py", line 38, in __init__
    raise Exception(
Exception: Put the Cohere API key in the COHERE_API_KEY environment variable (this was empty)
                 e.g.: export COHERE_API_KEY="XXXXXXX"
(garak) leod@mac622226 garak % export COHERE_API_KEY="PhVB[...]"
(garak) leod@mac622226 garak % python3 -m garak -m cohere -p test.Blank                        
garak LLM probe v0.9 ( https://github.com/leondz/garak ) at 2023-06-08T22:25:57.242848
📜 reporting to garak.414265.jsonl
🦜 loading generator: Cohere: command
🕵️  queue of probes: test.Blank
```

Did that work for you?

**Comment by leondz** [comment]
I get the same only if I also include the `sudo` like you. This doesn't need to be run as `root`, but that aside, could you try either also setting the env var in your root environment, or running it without sudo?
