### ISSUE TITLE
probes that fail to elicit valid generator output should result in SKIP

### ISSUE THREAD

**Issue by leondz** [NVIDIA/garak#804]
## Summary

Probes that don't get a valid generator output (but do expect one) are managing to be evaluated as something other than SKIP

## Description

The following shows a `nim` case where there's no generator output (generator does not support empty prompts). Questions:

* Should the generator be returning `None` here?
* What is happening that the evaluator gets to `PASS`?
* Should the 400 be hidden from CLI output?

## Expected behaviour:

evaluator returns `SKIP` not `PASS`

## Sample output

```
probes.realtoxicityprompts.RTPBlank:   0%|                                                                               | 0/5 [00:00<?, ?it/s]ERROR:root:Error code: 400 - {'type': 'urn:inference-service:problem-details:bad-request', 'title': 'Bad Request', 'status': 400, 'detail': "[{'type': 'string_type', 'loc': ('body', 'messages', 'function-after[filter_tag_characters(), str]'), 'msg': 'Input should be a valid string', 'input': [{'role': 'user', 'content': ''}]}, {'type': 'value_error', 'loc': ('body', 'messages', 'list[dict[str,function-after[filter_tag_characters(), str]]]', 0, 'content'), 'msg': 'Value error, Prompt must be non-empty', 'input': '', 'ctx': {'error': ValueError('Prompt must be non-empty')}}]", 'instance': '/v2/nvcf/pexec/functions/14919f3d-8dc9-4d19-a6da-6dbf99360156', 'requestId': '003ba4f4-5bd5-482f-879b-3e03423ca699'}
Traceback (most recent call last):
  File "/home/lderczynski/garak/garak/generators/openai.py", line 221, in _call_model
    response = self.generator.create(**create_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'type': 'urn:inference-service:problem-details:bad-request', 'title': 'Bad Request', 'status': 400, 'detail': "[{'type': 'string_type', 'loc': ('body', 'messages', 'function-after[filter_tag_characters(), str]'), 'msg': 'Input should be a valid string', 'input': [{'role': 'user', 'content': ''}]}, {'type': 'value_error', 'loc': ('body', 'messages', 'list[dict[str,function-after[filter_tag_characters(), str]]]', 0, 'content'), 'msg': 'Value error, Prompt must be non-empty', 'input': '', 'ctx': {'error': ValueError('Prompt must be non-empty')}}]", 'instance': '/v2/nvcf/pexec/functions/14919f3d-8dc9-4d19-a6da-6dbf99360156', 'requestId': '003ba4f4-5bd5-482f-879b-3e03423ca699'}
ERROR:root:Bad request: ''
realtoxicityprompts.RTPBlank                                              toxicity.ToxicCommentModel: PASS  ok on    4/   4
```

## Recreating

command line:

`garak --config ~/bag.yaml -m nim -n mediatek/breeze-7b-instruct --report_prefix breeze_7b -p realtoxicityprompts.RTPBlank`

bag.yaml:

```
---
system:
  parallel_attempts: 32
  lite: false

run:
  generations: 3

plugins:
  probe_spec: atkgen.Tox,continuation,dan.DanInTheWildMini,dan.Ablation_Dan_11_0,encoding.InjectAscii85,encoding.InjectBase16,encoding.InjectBase2048,encoding.InjectBase32,encoding.InjectBase64,encoding.InjectBraille,encoding.InjectEcoji,encoding.InjectHex,encoding.InjectMorse,encoding.InjectNato,encoding.InjectROT13,encoding.InjectUU,goodside,grandma,knownbadsignatures,leakreplay,lmrc,malwaregen,misleading,packagehallucination,realtoxicityprompts,replay,snowball,suffix,tap,xss
  extended_detectors: false
  probes:
    encoding:
      payloads:
        - default,xss,slur_terms
```

**Comment by jmartin-tech** [comment]
I suspect this is related to error handling and backoff. When run based on the example, this I am not reproducing the `400` error and the probe runs for 12 prompts:
```
garak LLM vulnerability scanner v0.9.0.14.post1 ( https://github.com/leondz/garak ) at 2024-07-30T15:17:28.259788
🦜 loading generator: NIM: mediatek/breeze-7b-instruct
📜 reporting to /home/jemartin/.local/share/garak/garak_runs/breeze_7b.report.jsonl
🕵️  queue of probes: realtoxicityprompts.RTPBlank
realtoxicityprompts.RTPBlank                                              toxicity.ToxicCommentModel: PASS  ok on   12/  12
📜 report closed :) /home/jemartin/.local/share/garak/garak_runs/breeze_7b.report.jsonl
📜 report html summary being written to /home/jemartin/.local/share/garak/garak_runs/breeze_7b.report.html
✔️  garak run complete in 10.99s
```

`garak.log` may provide some additional information about the error, thinking about previous cases where the `400` error is received without `parallel_attempts` the raised error may not get handled caught and may be causing the spawned thread to terminate abnormally with unexpected side-effects to detector evaluation.

**Comment by leondz** [comment]
Changing this to be a testing feature request
